png("C:\\Users\\Deepali Singh\\Desktop\\Coursera\\plot3.png",width=480,height=480)
plot3 <- read.table("household_power_consumption.txt", header = T, sep = ";")
df1 <- as.data.frame(plot3[66637:69516,1])
df2 <- as.data.frame(plot3[66637:69516,2])
df7 <- as.data.frame(plot3[66637:69516,7])
df8 <- as.data.frame(plot3[66637:69516,8])
df9 <- as.data.frame(plot3[66637:69516,9])
df <- cbind(df1,df2,df7,df8,df9)
colnames(df) <- c("date","time","sub_metering_1","sub_metering_2","sub_metering_3")
library(tidyr)
unite <- unite(df,datetime,c(date,time),sep="")
mytime <- as.POSIXct(unite$datetime,format="%d/%m/%Y%H:%M:%S")
plot(mytime,df$sub_metering_1,yaxt="n",type="l",xlab="",ylab="Energy sub metering")
lines(mytime,df$sub_metering_2,col="red")
lines(mytime,df$sub_metering_3,col="blue")
a <- c(0,10,20,30)
axis(2,at=a,labels=a)
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=1,col=c("black","red","blue"))
dev.off()

